### ISSUE TITLE
Dashboard crashes on Insights page

### ISSUE THREAD

**Issue by nightsh** [CivicActions/edscrapers#210]
Leaving a stack trace from the server here:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1461, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1341, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/usr/local/lib/python3.7/site-packages/edscrapers-1.0.0-py3.7.egg/edscrapers/tools/dashboard/app.py", line 146, in render_page_content
    return insights.generate_split_layout()
  File "/usr/local/lib/python3.7/site-packages/edscrapers-1.0.0-py3.7.egg/edscrapers/tools/dashboard/pages/insights.py", line 474, in generate_split_layout
    'data': p.get_datasets_bars_portal_data(),
  File "/usr/local/lib/python3.7/site-packages/edscrapers-1.0.0-py3.7.egg/edscrapers/tools/dashboard/pages/insights.py", line 365, in get_datasets_bars_portal_data
    legend_str = '<br>'.join(textwrap.wrap(title, width=20))
  File "/usr/local/lib/python3.7/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/usr/local/lib/python3.7/textwrap.py", line 351, in wrap
    chunks = self._split_chunks(text)
  File "/usr/local/lib/python3.7/textwrap.py", line 337, in _split_chunks
    text = self._munge_whitespace(text)
  File "/usr/local/lib/python3.7/textwrap.py", line 154, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
AttributeError: 'NoneType' object has no attribute 'expandtabs'
```

**Comment by higorspinto** [comment]
@nightsh the CKAN_HOST variable is set to `https://us-ed-scraping.ckan.io/` ? This instance seems a bit outdated without updates on the action `ed_scraping_dashboard`.

By the way, this bug is fixed here: https://github.com/CivicActions/edscrapers/pull/212
